export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const REMOVE_FACTOR = 'REMOVE_FACTOR';
export const SET_INCLUDED_TABLE = 'SET_INCLUDED_TABLE';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
